import type { Section } from '../schema';

export const cppSections: Section[] = [
  {
    id: 'c-unit1',
    courseId: 'cpp',
    order: 1,
    title: { en: 'Unit 1: The Virtual Cafe', bn: 'ইউনিট ১: ভার্চুয়াল ক্যাফে' },
    description: { en: 'In/Out, variables, and strings.', bn: 'ইন/আউট, ভেরিয়েবল এবং স্ট্রিং।' },
    icon: 'MessageSquare',
    color: 'bg-duo-green',
    lessonIds: ['c1-hello', 'c1-input', 'c1-vars', 'c1-exam'],
  },
  {
    id: 'c-unit2',
    courseId: 'cpp',
    order: 2,
    title: { en: 'Unit 2: The Profit Genie', bn: 'ইউনিট ২: দ্য প্রফিট জিনি' },
    description: { en: 'Math operators and data types.', bn: 'ম্যাথ অপারেটর এবং ডাটা টাইপ।' },
    icon: 'Calculator',
    color: 'bg-duo-blue',
    lessonIds: ['c2-math', 'c2-types', 'c2-exam'],
  },
  {
    id: 'c-unit3',
    courseId: 'cpp',
    order: 3,
    title: { en: 'Unit 3: Synapse Recall', bn: 'ইউনিট ৩: সিন্যাপস রিকল' },
    description: { en: 'Iterative review of Units 1 & 2.', bn: 'ইউনিট ১ এবং ২ এর ইটারেটিভ রিভিশন।' },
    icon: 'Brain',
    color: 'bg-duo-purple',
    lessonIds: ['c3-recall-1', 'c3-recall-2', 'c3-exam'],
  },
  {
    id: 'c-unit4',
    courseId: 'cpp',
    order: 4,
    title: { en: 'Unit 4: Branching Paths', bn: 'ইউনিট ৪: ব্রাঞ্চিং পাথ' },
    description: { en: 'If/Else statements and logic.', bn: 'If/Else স্টেটমেন্ট এবং লজিক।' },
    icon: 'GitBranch',
    color: 'bg-duo-orange',
    lessonIds: ['c4-if', 'c4-else', 'c4-exam'],
  },
  {
    id: 'c-unit5',
    courseId: 'cpp',
    order: 5,
    title: { en: 'Unit 5: Logic Gates', bn: 'ইউনিট ৫: লজিক গেটস' },
    description: { en: 'And, Or, Not operator chains.', bn: 'And, Or, Not অপারেটর চেইন।' },
    icon: 'Binary',
    color: 'bg-duo-red',
    lessonIds: ['c5-and', 'c5-or', 'c5-exam'],
  },
  {
    id: 'c-unit6',
    courseId: 'cpp',
    order: 6,
    title: { en: 'Unit 6: Cycle Master', bn: 'ইউনিট ৬: সাইকেল মাস্টার' },
    description: { en: 'For and While loops in C++.', bn: 'সি++ এ For এবং While লুপ।' },
    icon: 'Repeat',
    color: 'bg-duo-gold',
    lessonIds: ['c6-for', 'c6-while', 'c6-exam'],
  },
  {
    id: 'c-unit7',
    courseId: 'cpp',
    order: 7,
    title: { en: 'Unit 7: Deep Context', bn: 'ইউনিট ৭: ডিপ কনটেক্সট' },
    description: { en: 'Full logic and flow review.', bn: 'সম্পূর্ণ লজিক এবং ফ্লো রিভিশন।' },
    icon: 'RotateCcw',
    color: 'bg-[#58cc02]',
    lessonIds: ['c7-review-1', 'c7-review-2', 'c7-exam'],
  },
  {
    id: 'c-unit8',
    courseId: 'cpp',
    order: 8,
    title: { en: 'Unit 8: Data Clusters', bn: 'ইউনিট ৮: ডাটা ক্লাস্টার' },
    description: { en: 'Arrays and String storage.', bn: 'অ্যারে এবং স্ট্রিং স্টোরেজ।' },
    icon: 'List',
    color: 'bg-[#1cb0f6]',
    lessonIds: ['c8-arrays', 'c8-strings', 'c8-exam'],
  },
  {
    id: 'c-unit9',
    courseId: 'cpp',
    order: 9,
    title: { en: 'Unit 9: Machine Modules', bn: 'ইউনিট ৯: মেশিন মডিউল' },
    description: { en: 'Functions and modular build.', bn: 'ফাংশন এবং মডুলার বিল্ড।' },
    icon: 'Zap',
    color: 'bg-[#ff4b4b]',
    lessonIds: ['c9-func', 'c9-params', 'c9-exam'],
  },
  {
    id: 'c-unit10',
    courseId: 'cpp',
    order: 10,
    title: { en: 'Unit 10: The Empire Build', bn: 'ইউনিট ১০: দ্য এম্পায়ার বিল্ড' },
    description: { en: 'Your final showcase step-by-step!', bn: 'আপনার চূড়ান্ত শোকেস ধাপে ধাপে!' },
    icon: 'Trophy',
    color: 'bg-duo-gold',
    lessonIds: ['c10-start', 'c10-logic', 'p10-ui', 'p10-finish'],
  },
];
