import type { Section } from '../schema';

export const pythonSections: Section[] = [
  {
    id: 'p-unit1',
    courseId: 'python',
    order: 1,
    title: { en: 'Unit 1: The Chatterbox Bot', bn: 'ইউনিট ১: চ্যাটারবক্স বট' },
    description: { en: 'Master print(), input(), and variables.', bn: 'প্রিন্ট, ইনপুট এবং ভেরিয়েবল আয়ত্ত করুন।' },
    icon: 'MessageSquare',
    color: 'bg-duo-green',
    lessonIds: ['p1-hello', 'p1-input', 'p1-vars', 'p1-exam'],
  },
  {
    id: 'p-unit2',
    courseId: 'python',
    order: 2,
    title: { en: 'Unit 2: Genie Calculator', bn: 'ইউনিট ২: জিনি ক্যালকুলেটর' },
    description: { en: 'Numbers, operators, and data types.', bn: 'সংখ্যা, অপারেটর এবং ডাটা টাইপ।' },
    icon: 'Calculator',
    color: 'bg-duo-blue',
    lessonIds: ['p2-math', 'p2-types', 'p2-exam'],
  },
  {
    id: 'p-unit3',
    courseId: 'python',
    order: 3,
    title: { en: 'Unit 3: Memory Recall', bn: 'ইউনিট ৩: মেমোরি রিকল' },
    description: { en: 'Prove you remember Units 1 & 2.', bn: 'ইউনিট ১ এবং ২ এর পড়া মনে আছে কিনা প্রমাণ করুন।' },
    icon: 'Brain',
    color: 'bg-duo-purple',
    lessonIds: ['p3-recall-1', 'p3-recall-2', 'p3-exam'],
  },
  {
    id: 'p-unit4',
    courseId: 'python',
    order: 4,
    title: { en: 'Unit 4: Hero\'s Quest', bn: 'ইউনিট ৪: হিরো\'স কোয়েস্ট' },
    description: { en: 'If/Else logic and conditions.', bn: 'If/Else লজিক এবং কন্ডিশন।' },
    icon: 'GitBranch',
    color: 'bg-duo-orange',
    lessonIds: ['p4-if', 'p4-else', 'p4-exam'],
  },
  {
    id: 'p-unit5',
    courseId: 'python',
    order: 5,
    title: { en: 'Unit 5: Boolean Logic', bn: 'ইউনিট ৫: বুলিয়ান লজিক' },
    description: { en: 'And, Or, and Not logic loops.', bn: 'And, Or এবং Not লজিক লুপ।' },
    icon: 'Binary',
    color: 'bg-duo-red',
    lessonIds: ['p5-and', 'p5-or', 'p5-exam'],
  },
  {
    id: 'p-unit6',
    courseId: 'python',
    order: 6,
    title: { en: 'Unit 6: Loop-de-Loop', bn: 'ইউনিট ৬: লুপ-ডি-লুপ' },
    description: { en: 'Iterating tasks with For and While.', bn: 'For এবং While এর মাধ্যমে কাজ পুনরাবৃত্তি করা।' },
    icon: 'Repeat',
    color: 'bg-duo-gold',
    lessonIds: ['p6-for', 'p6-while', 'p6-exam'],
  },
  {
    id: 'p-unit7',
    courseId: 'python',
    order: 7,
    title: { en: 'Unit 7: Deep Recall', bn: 'ইউনিট ৭: ডিপ রিকল' },
    description: { en: 'Revision of all logic and flow.', bn: 'লজিক এবং ফ্লো এর রিভিশন।' },
    icon: 'RotateCcw',
    color: 'bg-[#58cc02]',
    lessonIds: ['p7-review-1', 'p7-review-2', 'p7-exam'],
  },
  {
    id: 'p-unit8',
    courseId: 'python',
    order: 8,
    title: { en: 'Unit 8: Inventory Master', bn: 'ইউনিট ৮: ইনভেন্টরি মাস্টার' },
    description: { en: 'Lists and basic collections.', bn: 'লিস্ট এবং বেসিক কালেকশন।' },
    icon: 'List',
    color: 'bg-[#1cb0f6]',
    lessonIds: ['p8-lists', 'p8-dicts', 'p8-exam'],
  },
  {
    id: 'p-unit9',
    courseId: 'python',
    order: 9,
    title: { en: 'Unit 9: Spell Casting', bn: 'ইউনিট ৯: স্পেল কাস্টিং' },
    description: { en: 'Functions and reusable modules.', bn: 'ফাংশন এবং পুনরায় ব্যবহারযোগ্য মডিউল।' },
    icon: 'Zap',
    color: 'bg-[#ff4b4b]',
    lessonIds: ['p9-func', 'p9-args', 'p9-exam'],
  },
  {
    id: 'p-unit10',
    courseId: 'python',
    order: 10,
    title: { en: 'Unit 10: The Grand Showcase', bn: 'ইউনিট ১০: দ্য গ্র্যান্ড শোকেস' },
    description: { en: 'Build your final step-by-step project!', bn: 'আপনার চূড়ান্ত প্রজেক্ট ধাপে ধাপে তৈরি করুন!' },
    icon: 'Trophy',
    color: 'bg-duo-gold',
    lessonIds: ['p10-start', 'p10-logic', 'p10-ui', 'p10-finish'],
  },
];
